# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c170f44cd6faf54a43fead9f092dd16763c12f60f279d835e4dfcf6cb6a8d2ed9714bca8cdd1e736a6f948abf2526b4e2216e180a183b9a712b57699f83caf73

test:
  secret_key_base: 2e49eb2504dcf00a6b82e99956ecde486e0f2465576dfc6d2aeeb5b89b57a5839ac92ef29b568ac3c8f31b6c1ce34ebacec57f086ceabba2505818abdd52c752

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
